### ISSUE TITLE
crash on iphone 6s 13.7

### ISSUE THREAD

**Issue by xiaopigpig** [changsanjiang/SJMediaCacheServer#10]
![截屏2020-11-26 下午7 25 24](https://user-images.githubusercontent.com/72684830/100350872-294c8e80-301d-11eb-841b-0ac65648189b.png)
播放视频时
error message:
Incorrect NSStringEncoding value 0x0000 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future.

**Comment by changsanjiang** [comment]
@xiaopigpig  更新到最新的再试一下吧
