### ISSUE TITLE
使用ijkplayer时，部分视频无法播放。

### ISSUE THREAD

**Issue by syq7970** [changsanjiang/SJMediaCacheServer#12]
视频原始地址： https://1500002838.vod2.myqcloud.com/438299a5vodtranscq1500002838/a78b80b45285890810696485191/v.f100030.mp4

server转换出来的地址：
http://127.0.0.1:2000/438299a5vodtranscq1500002838/a78b80b45285890810696485191/v.f100030.mp4?url=aHR0cHM6Ly8xNTAwMDAyODM4LnZvZDIubXlxY2xvdWQuY29tLzQzODI5OWE1dm9kdHJhbnNjcTE1MDAwMDI4MzgvYTc4YjgwYjQ1Mjg1ODkwODEwNjk2NDg1MTkxL3YuZjEwMDAzMC5tcDQ=

播放器提示播放失败。

**Comment by changsanjiang** [comment]
好的, 我瞅一下

**Comment by changsanjiang** [comment]
@syq7970 已修复, 待会我更新一下pod
