### ISSUE TITLE
prefetchWithURL 不支持断点续传

### ISSUE THREAD

**Issue by bird-xiong** [changsanjiang/SJMediaCacheServer#15]
使用 prefetchWithURL 加载一个视频时，如果中途中断下载（cancel 或者杀掉 app），下次再继续调用 prefetchWithURL 加载同一个视频时会出现 “请求range参数错误!” 异常，此时必须手动清除缓存，再重新下载该视频，希望这块逻辑优化一下

**Comment by changsanjiang** [comment]
@bird-xiong 来个可以复现这个问题的demo或者链接吧， 我直接测一下

**Comment by bird-xiong** [comment]
@changsanjiang  https://github.com/bird-xiong/PrefetchTest

**Comment by changsanjiang** [comment]
@bird-xiong  我更新一下， 还遇到其他问题了吗

**Comment by changsanjiang** [comment]
@bird-xiong 已修复，v1.4.1
