### ISSUE TITLE
m3u8 url not working

### ISSUE THREAD

**Issue by jitesh-sharma** [changsanjiang/SJMediaCacheServer#16]
@changsanjiang @CrystalBlack other URLs of m3u8 format not working for cache and playback URL. Only dummy URLs already added in app example are working. could you please suggest how can we use this m3u8 cache library at our end?
 exam ple urls 
https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

**Comment by changsanjiang** [comment]
Hi @jitesh-sharma , now you can try it with the new version [v1.4.2](https://github.com/changsanjiang/SJMediaCacheServer/releases/tag/1.4.2).

**Comment by jitesh-sharma** [comment]
The video URL is working now but without audio (mute video is playing). Audio is not working with video. please check
