### ISSUE TITLE
The video URL is working now but without audio (mute video is playing). Audio is not working with video. please check

### ISSUE THREAD

**Issue by jitesh-sharma** [changsanjiang/SJMediaCacheServer#17]
The video URL is working now but without audio (mute video is playing). Audio is not working with video. please check

_Originally posted by @jitesh-sharma in https://github.com/changsanjiang/SJMediaCacheServer/issues/16#issuecomment-780778986_

**Comment by changsanjiang** [comment]
I have checked and will submit updates later

**Comment by changsanjiang** [comment]
Please try again with the new version https://github.com/changsanjiang/SJMediaCacheServer/releases/tag/1.5.0
