### ISSUE TITLE
导入出错

### ISSUE THREAD

**Issue by zzzy11** [changsanjiang/SJMediaCacheServer#2]
导入的包含CocoaHTTPServer 出现Implicit declaration of function 'LOG_OBJC_MAYBE' is invalid in C99的错误

**Comment by changsanjiang** [comment]
替换一下
[HTTPLogging.h.zip](https://github.com/changsanjiang/SJMediaCacheServer/files/4923490/HTTPLogging.h.zip)

**Comment by zzzy11** [comment]
替换后，还是不行。。

**Comment by changsanjiang** [comment]
用这个, 刚才那个发错了: [HTTPLogging.h.zip](https://github.com/changsanjiang/SJMediaCacheServer/files/4923947/HTTPLogging.h.zip)

**Comment by zzzy11** [comment]
好了，谢谢
