### ISSUE TITLE
prefetching not working properly.

### ISSUE THREAD

**Issue by jitesh-sharma** [changsanjiang/SJMediaCacheServer#20]
@changsanjiang Precaching is not working properly. Following some scenarios/use cases in which preaching is not working :

Only app dummy URLs are preached properly as per my testing. When we are using other m3u8 URLs then preaching is not working. **Steps**:
In AppDelegate, we have cleared all caches.
From ViewController we pass the Videos array to VideoFeedViewController and play only the first video and code for prefetching all videos in viewDidLoad. After completing prefetching we switch off the Internet and scroll down to play offline videos (prefetched videos). But only app URLs (SJMediaCacheServer app demo URLs) are prefetched and they will play, but our m3u8 URLs are not playing. 
After that, we start our internet connection, and our URLs still not playing. Even sometimes app URLs(SJMediaCacheServer app demo URLs) are also not playing. The only option to play URLs is: kill the app and again start.

The second scenario is: if we have some URLs already cached, then they should play, even with no internet connection. But they are not working as expected.  
 
I am sharing one demo project in which we have two arrays in ViewController Class: **videoArray** and **video1Array**. And passed in the **action_videoFeed** method.  **videoArray** contains all dummy URLs working fine in prefetching, But when we pass **video1Array** then only initial URLs(SJMediaCacheServer app demo URLs) will be prefetched and after that our URLs will not be prefetched.

Please check I will share one demo project for that to your email address.

**Comment by jitesh-sharma** [comment]
I have shared a demo project for debugging the above issue.

**Comment by jitesh-sharma** [comment]
@changsanjiang if we have some URL already prefetch (or partially prefetch) and the internet connection is off then we should have to only play last prefetch data instead of trying to fetch more data from a server. Because the library tries to prefetch more data in off connection and already prefetch data does corrupt and not play offline. This is also one scenario.

**Comment by jitesh-sharma** [comment]
@changsanjiang we have already some played video but again when we scroll to that video. That starts loading again instead of playing from the last preload data. This is one more scenario of prefetching.

**Comment by changsanjiang** [comment]
@jitesh-sharma I fixed this bug in the new version [1.5.2](https://github.com/changsanjiang/SJMediaCacheServer/releases/tag/1.5.2)
