### ISSUE TITLE
For some cases, the app still freeze and also prefetch is fails

### ISSUE THREAD

**Issue by jitesh-sharma** [changsanjiang/SJMediaCacheServer#21]
I have checked version 1.5.2. Following are my observations:-

1. In some cases, the app is still freezing. I am sharing with you a video of the demo project I have shared with you last time in your mail ID. Please check the mail for the attached video for the scenario.

2. I am using the following method to check the cache status.
                        if SJMediaCacheServer.shared().isStored(for: URL) {
                            print(true)
                        } else {
                            print(false)
                        }

Every time, getting false. Am I missing something or using it wrong method? Please let me know.

3. When I am using the app for a few minutes and scroll up/down for a lot of videos. After some time, playableURL stops playing videos (for Already cached and new URL both). Only blank space appears. It is the main issue because the user experience is broken in this case. 

4. I am getting some logs in the console like : 
**2021-02-26 12:41:41.955388+0530 SJCacheServerDemo[61466:4106476] [connection] nw_connection_add_timestamp_locked_on_nw_queue [C2] Hit maximum timestamp count, will start dropping events**

**{OptimizedCabacDecoder::UpdateBitStreamPtr} bitstream parsing error!!!!!!!!!!!!!!
{OptimizedCabacDecoder::EndSliceBody} bitstream parsing error!!!!!!!!!!!!!!
{OptimizedCabacDecoder::UpdateBitStreamPtr} bitstream parsing error!!!!!!!!!!!!!!
{OptimizedCabacDecoder::EndSliceBody} bitstream parsing error!!!!!!!!!!!!!!**

May help you in debugging the issue.

**Comment by jitesh-sharma** [comment]
@changsanjiang sometimes prefetch works and suddenly it starts to download every time video visible on the screen. Takes a lot of time to start even it's already prefetched before.

**Expected Behaviour**: After prefetching, AVPlayer starts the video immediately from cache with playbakURL, without buffer or downloading again.

**Comment by jitesh-sharma** [comment]
@changsanjiang Have you seen the prefetching issue? Why prefetched video (m3u8 URLs) doesn't work from the local cache without download again like the mp4 URL cache? Am I missing some step or handling? Please help me or suggest anything to handle this issue. I am stuck in the m3u8 prefetching issue.

**Comment by changsanjiang** [comment]
Hi @jitesh-sharma 

I fixed the freezing problem in the new version.

`SJMediaCacheServer.shared().isStored(for: URL)` the storage status of m3u cannot be correctly represented because the playlist may contain multiple variant playlists.

```m3u
 #EXTM3U
 #EXT-X-STREAM-INF:BANDWIDTH=1296,RESOLUTION=640x360
 https://.../640x360_1200.m3u8
 #EXT-X-STREAM-INF:BANDWIDTH=264,RESOLUTION=416x234
 https://.../416x234_200.m3u8
 #EXT-X-STREAM-INF:BANDWIDTH=464,RESOLUTION=480x270
 https://.../480x270_400.m3u8
 #EXT-X-STREAM-INF:BANDWIDTH=1628,RESOLUTION=960x540
 https://.../960x540_1500.m3u8
 #EXT-X-STREAM-INF:BANDWIDTH=2628,RESOLUTION=1280x720
 https://.../1280x720_2500.m3u8
```

I don’t have a good solution yet, may be resolved in a future version.

**Comment by jitesh-sharma** [comment]
@changsanjiang  we can cache URLs with a specific identifier(URL without suffix or variants). At the time of fetching the data from the cache, we can use the identifier (URL without suffix or variants). So we can play video without buffer immediately and after that  AVPlayer will automatically change the cache with the latest bandwidth.  At least initially file (.ts file) will be used from cache ignoring the variant. May this help to resolve the issue.
