### ISSUE TITLE
crash in HTTPConnection.m file

### ISSUE THREAD

**Issue by jitesh-sharma** [changsanjiang/SJMediaCacheServer#23]
<img width="1439" alt="Screenshot 2021-03-03 at 1 23 36 PM" src="https://user-images.githubusercontent.com/25661009/109772419-f6b9bf80-7c23-11eb-9578-e2091f360d54.png">
  
if we navigate fast from one screen to another screen. The app is crashing in the HHTPConnection class.

**Comment by jitesh-sharma** [comment]
@changsanjiang  so much of memory is used by the library when playing m3u8 URLs with playback URL
<img width="997" alt="Screenshot 2021-03-03 at 1 47 00 PM" src="https://user-images.githubusercontent.com/25661009/109775153-274f2880-7c27-11eb-9415-7123945ca025.png">

**Comment by changsanjiang** [comment]
@jitesh-sharma Please give me a demo project 😄

**Comment by jitesh-sharma** [comment]
@changsanjiang  in demo project we have only a static number of the video files and its fine in static URLs. But when we have a dynamic URL by fetching from the server (different URLs for every API call), In that case, the crash happened almost every time when navigating the screen fastly from one to another and API calls every time for new urls. 
For precausions, I have called everytime  **SJMediaCacheServer.shared().cancelAllPrefetchTasks()** to cancel the last running prefetch tasks. But no luck

**Comment by changsanjiang** [comment]
I fixed this bug in the new version 1.6.0
