### ISSUE TITLE
部分m3u8地址视频播放失败

### ISSUE THREAD

**Issue by Layney** [changsanjiang/SJMediaCacheServer#25]
比如：http://t-course-video.meipian.me/course/m3u8/1616048303_WfVo.m3u8?pm3u8/0/deadline/1616058658&e=1616058658&token=o8tYTtFAc2_SNrlYQw8lTsYT9B5IUXNBItafEj4f:E4hJNhhrS2C6SYiOWn1p8sY9-qY=

**Comment by changsanjiang** [comment]
@Layney  这个token过期了， 再来个链接吧

**Comment by Layney** [comment]
> @Layney 这个token过期了， 再来个链接吧

http://t-course-video.meipian.me/course/m3u8/1616048303_WfVo.m3u8?pm3u8/0/deadline/1616062583&e=1616062583&token=o8tYTtFAc2_SNrlYQw8lTsYT9B5IUXNBItafEj4f:FZzx2xB8Dyv7h24KOYEu3kD4Lco=

报错内容是
MCSProxyTask: <0x281b699b0>.prepare;
MCSProxyTask: <0x281b699b0>.error { error: Error Domain=lib.changsanjiang.SJMediaCacheServer.error Code=100000 "(null)" UserInfo={object=<NSMutableURLRequest: 0x28164f530> { URL: http://t-course-video.meipian.me//93TFIiekHPD1WxnfGO4K-H6jLFA=/ljyi2JnOTxeQqR5p7NLmmGqbva2b/000014.ts?e=1616062583&token=o8tYTtFAc2_SNrlYQw8lTsYT9B5IUXNBItafEj4f:FDBpgNn_8AmM0c6Cjy8exZoShEE }, reason=解析器为空, 索引文件可能未解析!} };

**Comment by changsanjiang** [comment]
这里改一下： 
https://github.com/changsanjiang/SJMediaCacheServer/commit/d7edaeaefe97cb5333e619b0784fa4589d0e19c2

**Comment by changsanjiang** [comment]
1.  这种带token，参数不固定的url 需要配置一下这个block，保证引用相同的缓存文件

```Objective-C
    SJMediaCacheServer.shared.resolveAssetIdentifier = ^NSString * _Nonnull(NSURL * _Nonnull URL) {
        return [URL.absoluteString stringByDeletingPathExtension];
    };
```

2. token过期也会导致请求失败。 配置请求用这个block： 
```Objective-C
    SJMediaCacheServer.shared.requestHandler = ^NSMutableURLRequest * _Nullable(NSMutableURLRequest * _Nonnull request) {
//       配置token
//        request setURL:...
        return request;
    };
```

**Comment by Layney** [comment]
> 1. 这种带token，参数不固定的url 需要配置一下这个block，保证引用相同的缓存文件
> 
> ```objc
>     SJMediaCacheServer.shared.resolveAssetIdentifier = ^NSString * _Nonnull(NSURL * _Nonnull URL) {
>         return [URL.absoluteString stringByDeletingPathExtension];
>     };
> ```
> 
> 1. token过期也会导致请求失败。 配置请求用这个block：
> 
> ```objc
>     SJMediaCacheServer.shared.requestHandler = ^NSMutableURLRequest * _Nullable(NSMutableURLRequest * _Nonnull request) {
> //       配置token
> //        request setURL:...
>         return request;
>     };
> ```

好的 感谢大佬指点

**Comment by Layney** [comment]
> 1. 这种带token，参数不固定的url 需要配置一下这个block，保证引用相同的缓存文件
> 
> ```objc
>     SJMediaCacheServer.shared.resolveAssetIdentifier = ^NSString * _Nonnull(NSURL * _Nonnull URL) {
>         return [URL.absoluteString stringByDeletingPathExtension];
>     };
> ```
> 
> 1. token过期也会导致请求失败。 配置请求用这个block：
> 
> ```objc
>     SJMediaCacheServer.shared.requestHandler = ^NSMutableURLRequest * _Nullable(NSMutableURLRequest * _Nonnull request) {
> //       配置token
> //        request setURL:...
>         return request;
>     };
> ```

https://zuikzy.603ee.com/2019/05/06/Et6dCHH62ojQBCqB/playlist.m3u8?pm3u8/0/deadline/1616122998&e=1616122998&token=o8tYTtFAc2_SNrlYQw8lTsYT9B5IUXNBItafEj4f:cAZaDTeONN4hMlQHWcnldkWktGg=

**Comment by Layney** [comment]
> 1. 这种带token，参数不固定的url 需要配置一下这个block，保证引用相同的缓存文件
> 
> ```objc
>     SJMediaCacheServer.shared.resolveAssetIdentifier = ^NSString * _Nonnull(NSURL * _Nonnull URL) {
>         return [URL.absoluteString stringByDeletingPathExtension];
>     };
> ```
> 
> 1. token过期也会导致请求失败。 配置请求用这个block：
> 
> ```objc
>     SJMediaCacheServer.shared.requestHandler = ^NSMutableURLRequest * _Nullable(NSMutableURLRequest * _Nonnull request) {
> //       配置token
> //        request setURL:...
>         return request;
>     };
> ```

https://zuikzy.603ee.com/2019/05/06/Et6dCHH62ojQBCqB/playlist.m3u8?pm3u8/0/deadline/1616122998&e=1616122998&token=o8tYTtFAc2_SNrlYQw8lTsYT9B5IUXNBItafEj4f:cAZaDTeONN4hMlQHWcnldkWktGg=
这个地址又播放不了了 ？

**Comment by changsanjiang** [comment]
可以了

**Comment by Layney** [comment]
http://course-video.meipian.me/course/m3u8/1616725104_HY3n.m3u8?pm3u8/0/deadline/1616731262&e=1616731262&token=o8tYTtFAc2_SNrlYQw8lTsYT9B5IUXNBItafEj4f:9u2Wa_SbW3ZeiPxJoztZ-3SkrUs=
这个链接为啥又解析不了 。。。

**Comment by changsanjiang** [comment]
这个URL比较奇特， 我测试一下

**Comment by changsanjiang** [comment]
这里改一下吧： https://github.com/changsanjiang/SJMediaCacheServer/commit/075e939888f574e62ea21fdb22d0ed481beb712b#

**Comment by Layney** [comment]
很奇怪 我们测试环境地址就是可以正常解析的 ：
http://t-course-video.meipian.me/course/m3u8/1616727566_R424.m3u8?pm3u8/0/deadline/1616733211&e=1616733211&token=o8tYTtFAc2_SNrlYQw8lTsYT9B5IUXNBItafEj4f:eLAFTUqODvDhvLDPKbt2RCPxTv4=
