### ISSUE TITLE
可以加一个error报错统一block出来吗

### ISSUE THREAD

**Issue by Layney** [changsanjiang/SJMediaCacheServer#27]
有些业务场景需要针对播放器下载缓存或者解码过程中失败或报错的话 播放器上面提示某种交互。
针对这种场景，可以加一个error报错统一block出来吗，我们不方便直接修改源码，这样不利于后期的更新🙏

**Comment by changsanjiang** [comment]
恩, 周末会更新一下

**Comment by Layney** [comment]
> 恩, 周末会更新一下
好的

**Comment by Layney** [comment]
> 恩, 周末会更新一下

大佬加好了吗 😸

**Comment by changsanjiang** [comment]
MCSDownload.h

MCSDownload.shared.errorCallback
