### ISSUE TITLE
内否抛弃掉CocoaHTTPServer，或者直接代码引入

### ISSUE THREAD

**Issue by yaojunguang** [changsanjiang/SJMediaCacheServer#3]
我都一直想自己写一个支持M3u8的，你添加这个很赞，不过
CocoaHTTPServer这个库已经废弃掉了，我是swift项目，引入编译一堆错误，没法使用
具体的错误可参考这个 https://www.jianshu.com/p/b693d660acc1

**Comment by changsanjiang** [comment]
已处理(v1.3.1)
