### ISSUE TITLE
播放m3u8视频一段时间后，会报Domain=NSURLErrorDomain Code=-1005 "网络连接已中断。"错误

### ISSUE THREAD

**Issue by wangleihi** [changsanjiang/SJMediaCacheServer#40]
播放m3u8视频一段时间后，会报Domain=NSURLErrorDomain Code=-1005 "网络连接已中断。"错误

Domain=NSURLErrorDomain Code=-1005 "网络连接已中断。" UserInfo={NSLocalizedDescription=网络连接已中断。, NSErrorFailingURLStringKey=http://course-video.meipian.me/3auYnFiwCH32B5AV8r0yv_F1GYM=/ltTu3pgLGYLcPsXQ8yD8ol-AwdOP/000072.ts?e=1633946970&token=o8tYTtFAc2_SNrlYQw8lTsYT9B5IUXNBItafEj4f:jiMZfiXrIB3RArORB_Hr95uu0i4, NSErrorFailingURLKey=http://course-video.meipian.me/3auYnFiwCH32B5AV8r0yv_F1GYM=/ltTu3pgLGYLcPsXQ8yD8ol-AwdOP/000072.ts?e=1633946970&token=o8tYTtFAc2_SNrlYQw8lTsYT9B5IUXNBItafEj4f:jiMZfiXrIB3RArORB_Hr95uu0i4, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <0F6B0733-7E3C-4FB4-BF9A-BE92FD7FB31D>.<236>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0F6B0733-7E3C-4FB4-BF9A-BE92FD7FB31D>.<236>, NSUnderlyingError=0x281879710 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x283402df0 [0x25ffdd430]>{length = 16, capacity = 16, bytes = 0x10022382c0a8002c0000000000000000}}}}
MCSProxyTask: <0x281a60e40>.close { after (36.473433) seconds };

很大概率会出现

**Comment by xuxueyong** [comment]
这个有结论吗？

**Comment by changsanjiang** [comment]
尝试新版本 2.0.1
