### ISSUE TITLE
[HLSAsset totalLength]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by trial** [changsanjiang/SJMediaCacheServer#47]
https://europe.olemovienews.com/hls2timeofffmp4/20220718/sBmEtija/mp4/sBmEtija.mp4/master.m3u8
这个视频可以在safari正常播放，不启用缓存sjvideoplayer也没问题

启用缓存后

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[HLSAsset totalLength]: unrecognized selector sent to instance 0x2833f3f00'

**Comment by joealzhou** [comment]
我也遇见了

**Comment by changsanjiang** [comment]
已修复， 请尝试新版本 2.0.1
