### ISSUE TITLE
预加载视频失败了

### ISSUE THREAD

**Issue by jasparchan** [changsanjiang/SJMediaCacheServer#5]
Error Domain=lib.changsanjiang.SJMediaCacheServer.error Code=100002 "(null)" UserInfo={URL=https://v.suv666.com/test/material/a67363cde6a5ce0ac5f09ac2b6fdc6a5_360p.mp4, Request=<NSMutableURLRequest: 0x28388c430> { URL: https://v.suv666.com/test/material/a67363cde6a5ce0ac5f09ac2b6fdc6a5_360p.mp4 }, Response=<NSHTTPURLResponse: 0x283a7bf40> { URL: https://v.suv666.com/test/material/a67363cde6a5ce0ac5f09ac2b6fdc6a5_360p.mp4 } { Status Code: 206, Headers {
    "Accept-Ranges" =     (
        bytes
    );
    "Access-Control-Allow-Origin" =     (
        "*"
    );
    "Access-Control-Expose-Headers" =     (
        "X-Log, X-Reqid"
    );
    "Access-Control-Max-Age" =     (
        2592000
    );
    Age =     (
        2486964
    );
    "Ali-Swift-Global-Savetime" =     (
        1594710439
    );
    "Cache-Control" =     (
        "public, max-age=31536000"
    );
    Connection =     (
        "keep-alive"
    );

**Comment by changsanjiang** [comment]
已处理(v1.3.1)
