### ISSUE TITLE
prefetchWithURL 预加载 取消task引发的问题

### ISSUE THREAD

**Issue by TangBaoo** [changsanjiang/SJMediaCacheServer#54]
用prefetchWithURL来加载资源, 如果未下载完成前调用task cancel, 然后再次prefetchWithURL加载相同资源,会导致沙盒下载的MP4资源不是完成状态, 虽然提示下载完成了,但是沙盒文件里的文件没办法保存到相册,和导出资源

**Comment by KaiPisces** [comment]
![20220907154957](https://user-images.githubusercontent.com/13808303/188820994-d60feafe-4d7a-496f-ac79-525b166ae2a5.jpg)

**Comment by changsanjiang** [comment]
尝试新版本 2.0.0
