### ISSUE TITLE
如果m3u8的文件ts是url，会导致就算缓存好，播放的时候还是通过网络播放

### ISSUE THREAD

**Issue by chenfengfeng** [changsanjiang/SJMediaCacheServer#57]
通过这个地址可以复现这个问题：http://114.132.46.10:8888/down/rQMzi0sh7q6g.m3u8

**Comment by chenfengfeng** [comment]
研究了下源代码，判断是否下载，是通过ts的md5和url的md5对比，但我发的这个链接里面的ts是通过302重定向，导致url的md5会跟ts的不一致，导致没发现已经下载

**Comment by chenfengfeng** [comment]
有空的话，帮忙指导下怎么改能够快速实现，非常感谢～

**Comment by chenfengfeng** [comment]
我这边做了最粗糙的改造，创建name的时候，拿最初的url来做，这样可以避免url进行302导致md5不一致

**Comment by wutao66** [comment]
我也遇到这个问题，导致每次都会需要网络播放，你现在解决了没

**Comment by chenfengfeng** [comment]
@wutao66 我上面写了临时解决方案，不过因为我是因为url会进行302跳转导致，所以你需要根据你实际情况看看是否也是这样

**Comment by wutao66** [comment]
@chenfengfeng 我这边主要用的是阿里云的视频url，用他demo可以正常读到缓存，换到我项目就直接显示网络异常，不读缓存了，Task <515ABD68-9FDB-4AAA-A2B1-9E7933567D72>.<1> HTTP load failed, 0/0 bytes (error code: -1009 [1:50])，你有遇到这种情况吗

**Comment by chenfengfeng** [comment]
@wutao66 抱歉没看到信息，我没遇到这个情况

**Comment by changsanjiang** [comment]
新版本已修复 2.0.0
