### ISSUE TITLE
探讨一下用法

### ISSUE THREAD

**Issue by iOSleep** [changsanjiang/SJMediaCacheServer#6]
a问题：
不使用 cache，播放的同时，点击下载。会有两个请求。
同样的操作，如果使用 cache。一样有两个请求，区别可能是缓存下载的range，会相对小一些。
在这种情况下，如果用户一直看到视频结束，下载的流量就接近 2倍视频资源（先播放的那部分缓存了，下载的range从那部分之后发出），这样缓存提升较小。

b问题：
上面的场景是没有缓存完的情况，如果通过播放缓存完成，此时进行下载。那么相当于本地copy。但是此时不能清除cache里的源文件，否则cache就失效了（类似demo这种仍然能正常播放和seek是依赖了播放器的缓存，如果是大视频就....），补救措施是切换播放器的播放源到下载源，不好做到无缝衔接。

想问问作者使用的时候是如何应对这两个场景的

**Comment by changsanjiang** [comment]
a: 如果使用cache， 会同时处理播放器请求和下载请求(项目中的prefetch功能)， prefetch 的下载是分段的，一个文件分成多个段落一个一个的进行下载， 当某个段落下载完毕再接着请求下一段的数据。 在请求下一段数据时，会查询缓存(可能是播放器请求到的数据)这部分数据如果存在就不会再次请求了，如此循环直到本地有一份相对完整的缓存(可能是多个段落文件， 这些段落文件会在某个合适的时机被拼成单个完整文件);

b: 调用下载功能后， 得保护缓存不被删除，可以对缓存做个标记(项目中是 export功能)， 不能被管理类删除;
