### ISSUE TITLE
Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT

### ISSUE THREAD

**Issue by zdiovo** [changsanjiang/SJMediaCacheServer#64]
- IDE: Xcode 14.3
- Device : iPhone 11 XS Max
- iOS version : 16.4.1
- Warning Flie : MCSProxyServer.m
- Positon line :  83
- Code :
```
dispatch_semaphore_wait(_semaphore, DISPATCH_TIME_FOREVER);
```
- After playing 1~3 min，Xcode Warning infomation:
```
Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions
```
- After playing 5~6 min，console shows infomation：
```
Background Task 7 ("Called by SJMediaCacheServer, from -[MCSProxyServer _beginBackgroundTask]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```

**Comment by Leo-Smith** [comment]
我也遇到了，哈哈哈哈

Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions
PID: 12113, TID: 305019
Backtrace
=================================================================
3   SJMediaCacheServer                  0x000000010385b4e8 -[MCSTimer invalidate] + 36
4   SJMediaCacheServer                  0x000000010385c054 __47-[MCSProxyServer HTTPConnectionDidDieWithNote:]_block_invoke + 292
5   SJMediaCacheServer                  0x000000010385b344 __55-[MCSTimer initWithQueue:start:interval:repeats:block:]_block_invoke + 96
6   libdispatch.dylib                   0x0000000103919d50 _dispatch_client_callout + 16
7   libdispatch.dylib                   0x000000010391d208 _dispatch_continuation_pop + 756
8   libdispatch.dylib                   0x00000001039348d4 _dispatch_source_invoke + 1676
9   libdispatch.dylib                   0x000000010392a634 _dispatch_main_queue_drain + 848
10  libdispatch.dylib                   0x000000010392a2d4 _dispatch_main_queue_callback_4CF + 40
11  CoreFoundation                      0x000000018039a784 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
12  CoreFoundation                      0x0000000180394de4 __CFRunLoopRun + 1912
13  CoreFoundation                      0x0000000180394254 CFRunLoopRunSpecific + 584
14  GraphicsServices                    0x0000000188eb7c9c GSEventRunModal + 160
15  UIKitCore                           0x0000000104ba6ff0 -[UIApplication _run] + 868
16  UIKitCore                           0x0000000104baaf3c UIApplicationMain + 124
17  libswiftUIKit.dylib                 0x0000000103ff0454 $s5UIKit17UIApplicationMainys5Int32VAD_SpySpys4Int8VGGSgSSSgAJtF + 100
18  VideoChat                           0x0000000102879f84 $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 120
19  VideoChat                           0x0000000102879efc $s9VideoChat11AppDelegateC5$mainyyFZ + 44
20  VideoChat                           0x000000010287a000 main + 28

**Comment by changsanjiang** [comment]
新版本已修复 2.0.0
