### ISSUE TITLE
某些地址会导致生成两个文件夹，导致进度条从50%开始

### ISSUE THREAD

**Issue by chenfengfeng** [changsanjiang/SJMediaCacheServer#66]
播放地址：https://064.qgj899.com/20230618/zHGZLcGh/index.m3u8

麻烦看看

**Comment by chenfengfeng** [comment]
@changsanjiang 主要还是会导致removeExportAsset这个方法会删除不了真正有数据的文件夹

**Comment by changsanjiang** [comment]
尝试新版本看看: 2.0.0
