### ISSUE TITLE
Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_BACKGROUND. Investigate ways to avoid priority inversions

### ISSUE THREAD

**Issue by jozdee** [changsanjiang/SJMediaCacheServer#68]
Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_BACKGROUND. Investigate ways to avoid priority inversions
PID: 36563, TID: 14816524
Backtrace
=================================================================
3   996                                 0x0000000101792900 -[MCSPrefetchOperation _completeOperationIfExecuting] + 148
4   996                                 0x00000001017920a8 -[MCSPrefetchOperation prefetcher:didCompleteWithError:] + 72
5   996                                 0x0000000101758250 __40-[FILEPrefetcher _didCompleteWithError:]_block_invoke + 72
6   libdispatch.dylib                   0x0000000105f84520 _dispatch_call_block_and_release + 32
7   libdispatch.dylib                   0x0000000105f86038 _dispatch_client_callout + 20
8   libdispatch.dylib                   0x0000000105f96798 _dispatch_main_queue_drain + 1196
9   libdispatch.dylib                   0x0000000105f962dc _dispatch_main_queue_callback_4CF + 44
10  CoreFoundation                      0x0000000198783c28 A900B459-0127-379E-9CBA-0EAB9C5D559F + 625704
11  CoreFoundation                      0x0000000198765560 A900B459-0127-379E-9CBA-0EAB9C5D559F + 501088
12  CoreFoundation                      0x000000019876a3ec CFRunLoopRunSpecific + 612
13  GraphicsServices                    0x00000001d3c8035c GSEventRunModal + 164
14  UIKitCore                           0x000000019aaf6f58 7D57A1D1-856F-338D-97DB-880C4EC8B02E + 3788632
15  UIKitCore                           0x000000019aaf6bbc UIApplicationMain + 340
16  996                                 0x0000000100c6ac0c main + 124
17  dyld                                0x00000001b7c9cdec C3FC2EE4-367F-3086-BEB8-420AD442BF88 + 89580
SJMediaPlaybackController<0x28260e010>.TimeControlStatus.Playing
SJMediaPlaybackController<0x28260e010>.assetStatus.ReadyToPlay
2023-09-20 17:57:28.276042+0800 996[36563:14816705]  | JIGUANG | I - [JIGUANG] upload device token success, current token is : 11b7d3609fda48010a9cc82be026b061531077fb5ad0d9ccdf3c915aee96aad9
Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions
PID: 36563, TID: 14816524
Backtrace
=================================================================
3   996                                 0x0000000101793840 -[MCSTimer invalidate] + 36
4   996                                 0x0000000101794390 __47-[MCSProxyServer HTTPConnectionDidDieWithNote:]_block_invoke + 288
5   996                                 0x00000001017936f0 __55-[MCSTimer initWithQueue:start:interval:repeats:block:]_block_invoke + 88
6   libdispatch.dylib                   0x0000000105f86038 _dispatch_client_callout + 20

**Comment by changsanjiang** [comment]
新版本已修复 2.0.0
