### ISSUE TITLE
路径一样,参数不一样的视频.缓存只缓存了一个  这个怎么解决

### ISSUE THREAD

**Issue by yushenNO1** [changsanjiang/SJMediaCacheServer#72]

**Comment by yushenNO1** [comment]
https://gnjk.seudl.com/api/index.m3u8?m=1111111&t=1727587133&k=222222
https://gnjk.seudl.com/api/index.m3u8?m=222222&t=1727587133&k=333333

**Comment by changsanjiang** [comment]
设置 resolveAssetIdentifier, 返回 问号前面的url, 例如 https://gnjk.seudl.com/api/index.m3u8?m=1111111&t=1727587133&k=222222 返回 https://gnjk.seudl.com/api/index.m3u8

**Comment by yushenNO1** [comment]
[SJMediaCacheServer shared].resolveAssetIdentifier = ^NSString * _Nonnull(NSURL * _Nonnull URL) {
        NSString *url = weakSelf.playerUrl;
        if ([url containsString:@"?"]) {
            NSArray *ary = [url componentsSeparatedByString:@"?"];
            url = ary[0];
        }
        NSLog(@"url ===> %@",url);
        if (![url isNotBlank]) {
            return @"";
        }
        return url;
    };
添加了  还是只下载了一个视频源

**Comment by changsanjiang** [comment]
设置为空： [SJMediaCacheServer shared].resolveAssetIdentifier = nil;
