### ISSUE TITLE
m3u8 Xcode16.0  真机和模拟器 全部都会崩溃      2.0.1版本

### ISSUE THREAD

**Issue by ZYHB** [changsanjiang/SJMediaCacheServer#73]
测试链接：http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
![image](https://github.com/user-attachments/assets/c5957598-4e1c-4ed5-9585-6d5ad7ccd9db)

**Comment by changsanjiang** [comment]
已修复， 待会发个版本
