### ISSUE TITLE
2.0.0 以后版本，m3u8 无法缓存。2.0.0 之前的版本是好的。

### ISSUE THREAD

**Issue by InsectQY** [changsanjiang/SJMediaCacheServer#74]
地址链接: https://duanjushow.snail.com/28b9d5ca-d716-4546-913a-baecb4bb2184/AppleHLS1/5356815f14de144e37f327f7e4423c23_Ott_Hls_Ts_Avc_Aac_16x9_1280x720p_6.0Mbps_qvbr.m3u8

**Comment by changsanjiang** [comment]
我看一下

**Comment by changsanjiang** [comment]
@InsectQY  m3u8的响应头里面没加 content-length， 如果着急的话你先和后台商量看看能不能加上
