### ISSUE TITLE
countOfBytesAllCaches 方法总是返回 0

### ISSUE THREAD

**Issue by InsectQY** [changsanjiang/SJMediaCacheServer#75]
直接使用的 demo 链接地址。

**Comment by InsectQY** [comment]
<img width="1070" alt="iShot_2024-12-01_17 11 29" src="https://github.com/user-attachments/assets/4b0aeaf9-02e0-42e1-b56b-b2b60ac9225f">

**Comment by changsanjiang** [comment]
已修复， 待会发个版本
