### ISSUE TITLE
Assertion failed: (filenameExtension != nil) 崩溃

### ISSUE THREAD

**Issue by joealzhou** [changsanjiang/SJMediaCacheServer#78]
HLSAssetSegment<0x280511620>: 18 : dealloc; waring: readwrite retained.
Assertion failed: (filenameExtension != nil), function MCSMimeType, file MCSMimeType.m, line 20.

控制台有警告：
Warning: content read/write count is not zero. Content: HLSAssetSegment: <0x280b5a220> { totalLength: 938308, byteRange={0, 938308}, position: 0, length: 938308, readwriteCount: 1, filePath: /var/mobile/Containers/Data/Application/D9174657-07F1-419A-84F8-743BC1D86F48/Documents/com.SJMediaCacheServer.cache/596cb9114d03f715e19f14c1bb39d2cd/hls_938308_0_c312d68beb8e7e9e687f2cf510acc5b0.ts };
, Read/Write Count: 1

**Comment by greyspot09** [comment]
我也碰到了Assertion failed: (filenameExtension != nil), function MCSMimeType, file MCSMimeType.m, line 20. m3u8的源。2.0.0之后的版本会有问题

**Comment by changsanjiang** [comment]
尝试 2.0.7 看看

**Comment by yuanpc** [comment]
我这儿更新到2.0.7仍旧出现了这个问题，目前是发现  id<HLSItem> item = mSegmentItems[nodeIdentifier];获取item为nil导致，简单的作了下非空判断避免崩溃，具体原因还是不太明白。

**Comment by yuanpc** [comment]
> 尝试 2.0.7 看看

我这儿更新到2.0.7仍旧出现了这个问题，目前是发现 id item = mSegmentItems[nodeIdentifier];获取item为nil导致，简单的作了下非空判断避免崩溃，具体原因还是不太明白。

**Comment by changsanjiang** [comment]
有没有必现的url， 发我一个测试看看

**Comment by yuanpc** [comment]
> 有没有必现的url， 发我一个测试看看

邮箱发你了

**Comment by yuanpc** [comment]
> 尝试 2.0.7 看看

又仔细看了下，播放过程中达到了设置的最大缓存值然后调用了clear方法，导致mSegmentItems为nil，所以后续就导致MCSMimeType内崩溃；还有一种情况是有缓存时，_onPlaylist方法内也会触发这个崩溃，推测可能是586行   id<HLSItem> item = mSegmentItems[nodeIdentifier];获取失败导致，线上有检测到崩溃，但是未复现；
