### ISSUE TITLE
如何判断该视频是否已经有缓存了

### ISSUE THREAD

**Issue by xiaopigpig** [changsanjiang/SJMediaCacheServer#8]

**Comment by xiaopigpig** [comment]
//自问自答
NSString *name = [MCSURLRecognizer.shared resourceNameForURL:URL];
    NSString *cachePath = [MCSFileManager getResourcePathWithName:name];
    BOOL isHave = [MCSFileManager fileExistsAtPath:cachePath];

**Comment by changsanjiang** [comment]
新版有API了,  v1.3.1 
```Objective-C
    [SJMediaCacheServer.shared isStoredForURL:URL];
```

**Comment by KaiPisces** [comment]
方便暴露个方法直接取到缓存后到沙盒文件对应filepath吗
